# Generated by Django 5.2.1 on 2025-06-13 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='admin',
            field=models.OneToOneField(limit_choices_to={'role': 'organization_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='organization_administered', to=settings.AUTH_USER_MODEL),
        ),
    ]
